export default{
    state:{
        userImg:require('../assets/user.jpg'),
            tableData:[],
            tableLable:{
                name:"课程",
                totalBuy:"今日购买",
                monthBuy:"本月购买",
                totalBuy:"总购买"
            },
            countData:[
                {
                    name:"今日支付订单",
                    value:1234,
                    icon:"success",
                    color:"#2ec7c9",
                },
                {
                    name:"今日收藏订单",
                    value:120,
                    icon:"star-on",
                    color:"#ffb980",
                },
                {
                    name:"今日未支付订单",
                    value:1234,
                    icon:"s-goods",
                    color:"#5abdef",
                },
                 {
                    name:"本月支付订单",
                    value:1234,
                    icon:"success",
                    color:"#2ec7c9",
                },
                {
                    name:"本月收藏订单",
                    value:120,
                    icon:"star-on",
                    color:"#ffb980",
                },
                {
                    name:"本月未支付订单",
                    value:1234,
                    icon:"s-goods",
                    color:"#5abdef",
                },
            ],
            echartData:{
                order:{
                    xData:[],
                    series:[]
                },
                user:{
                    xData:[],
                    series:[]
                },
                video:{
                    series:[]
                }
            },
            tableData:[]
    },
    mutations:{
        setTableData(state,payload){
            state.tableData = payload
        }
    }
}